<?php

declare(strict_types=1);

namespace Modules\Core\database\seeders;

use Illuminate\Database\Seeder;
use Modules\Core\Models\City;
use Modules\Core\Models\Region;

class RegionsAndCitiesSeeder extends Seeder
{
    public function run(): void
    {
        $regionsData = [
            [
                'name' => ['uz' => 'Toshkent shahri', 'ru' => 'город Ташкент', 'en' => 'Tashkent city'],
                'cities' => [
                    ['uz' => 'Bektemir tumani', 'ru' => 'Бектемирский район', 'en' => 'Bektemir district'],
                    ['uz' => 'Mirzo Ulugʻbek tumani', 'ru' => 'Мирзо-Улугбекский район', 'en' => 'Mirzo Ulugbek district'],
                    ['uz' => 'Mirobod tumani', 'ru' => 'Мирабадский район', 'en' => 'Mirabad district'],
                    ['uz' => 'Olmazor tumani', 'ru' => 'Алмазарский район', 'en' => 'Almazar district'],
                    ['uz' => 'Sergeli tumani', 'ru' => 'Сергелийский район', 'en' => 'Sergeli district'],
                    ['uz' => 'Shayxontohur tumani', 'ru' => 'Шайхантаурский район', 'en' => 'Shayhantahur district'],
                    ['uz' => 'Uchtepa tumani', 'ru' => 'Учтепинский район', 'en' => 'Uchtepa district'],
                    ['uz' => 'Chilonzor tumani', 'ru' => 'Чиланзарский район', 'en' => 'Chilanzar district'],
                    ['uz' => 'Yakkasaroy tumani', 'ru' => 'Яккасарайский район', 'en' => 'Yakkasaray district'],
                    ['uz' => 'Yashnobod tumani', 'ru' => 'Яшнабадский район', 'en' => 'Yashnabad district'],
                    ['uz' => 'Yunusobod tumani', 'ru' => 'Юнусабадский район', 'en' => 'Yunusabad district'],
                    ['uz' => 'Yangihayot tumani', 'ru' => 'Янгихаётский район', 'en' => 'Yangihayot district'],
                ],
            ],
            [
                'name' => ['uz' => 'Toshkent viloyati', 'ru' => 'Ташкентская область', 'en' => 'Tashkent region'],
                'cities' => [
                    ['uz' => 'Angren', 'ru' => 'Ангрен', 'en' => 'Angren'],
                    ['uz' => 'Bekobod', 'ru' => 'Бекабад', 'en' => 'Bekabad'],
                    ['uz' => 'Chirchiq', 'ru' => 'Чирчик', 'en' => 'Chirchik'],
                    ['uz' => 'Olmaliq', 'ru' => 'Алмалык', 'en' => 'Almalyk'],
                    ['uz' => 'Yangiyo\'l', 'ru' => 'Янгиюль', 'en' => 'Yangiyul'],
                    ['uz' => 'Nurafshon', 'ru' => 'Нурафшан', 'en' => 'Nurafshan'],
                    ['uz' => 'Bekobod tumani', 'ru' => 'Бекабадский район', 'en' => 'Bekabad district'],
                    ['uz' => 'Boʻstonliq tumani', 'ru' => 'Бостанлыкский район', 'en' => 'Bostanlik district'],
                    ['uz' => 'Boʻka tumani', 'ru' => 'Букинский район', 'en' => 'Buka district'],
                    ['uz' => 'Qibray tumani', 'ru' => 'Кибрайский район', 'en' => 'Kibray district'],
                    ['uz' => 'Zangiota tumani', 'ru' => 'Зангиатинский район', 'en' => 'Zangiata district'],
                    ['uz' => 'Quyichirchiq tumani', 'ru' => 'Куйичирчикский район', 'en' => 'Quyi Chirchik district'],
                    ['uz' => 'Oqqoʻrgʻon tumani', 'ru' => 'Аккурганский район', 'en' => 'Akkurgan district'],
                    ['uz' => 'Ohangaron tumani', 'ru' => 'Ахангаранский район', 'en' => 'Ahangaran district'],
                    ['uz' => 'Parkent tumani', 'ru' => 'Паркентский район', 'en' => 'Parkent district'],
                    ['uz' => 'Piskent tumani', 'ru' => 'Пскентский район', 'en' => 'Piskent district'],
                    ['uz' => 'Toshkent tumani', 'ru' => 'Ташкентский район', 'en' => 'Tashkent district'],
                    ['uz' => 'Chinoz tumani', 'ru' => 'Чиназский район', 'en' => 'Chinaz district'],
                    ['uz' => 'Yuqorichirchiq tumani', 'ru' => 'Юкоричирчикский район', 'en' => 'Yuqori Chirchik district'],
                    ['uz' => 'Yangiyoʻl tumani', 'ru' => 'Янгиюльский район', 'en' => 'Yangiyul district'],
                ],
            ],
            [
                'name' => ['uz' => 'Andijon viloyati', 'ru' => 'Андижанская область', 'en' => 'Andijan region'],
                'cities' => [
                    ['uz' => 'Andijon', 'ru' => 'Андижан', 'en' => 'Andijan'],
                    ['uz' => 'Xonobod', 'ru' => 'Ханабад', 'en' => 'Khanabad'],
                    ['uz' => 'Asaka', 'ru' => 'Асака', 'en' => 'Asaka'],
                    ['uz' => 'Andijon tumani', 'ru' => 'Андижанский район', 'en' => 'Andijan district'],
                    ['uz' => 'Asaka tumani', 'ru' => 'Асакинский район', 'en' => 'Asaka district'],
                    ['uz' => 'Baliqchi tumani', 'ru' => 'Балыкчинский район', 'en' => 'Baliqchi district'],
                    ['uz' => 'Buloqboshi tumani', 'ru' => 'Булакбашинский район', 'en' => 'Buloqboshi district'],
                    ['uz' => 'Boʻz tumani', 'ru' => 'Бозский район', 'en' => 'Boz district'],
                    ['uz' => 'Jalolquduq tumani', 'ru' => 'Джалакудукский район', 'en' => 'Jalaquduq district'],
                    ['uz' => 'Izboskan tumani', 'ru' => 'Избасканский район', 'en' => 'Izboskan district'],
                    ['uz' => 'Ulugʻnor tumani', 'ru' => 'Улугнорский район', 'en' => 'Ulughnor district'],
                    ['uz' => 'Qoʻrgʻontepa tumani', 'ru' => 'Кургантепинский район', 'en' => 'Qurghantepa district'],
                    ['uz' => 'Marhamat tumani', 'ru' => 'Мархаматский район', 'en' => 'Marhamat district'],
                    ['uz' => 'Oltinkoʻl tumani', 'ru' => 'Алтынкульский район', 'en' => 'Altynkul district'],
                    ['uz' => 'Paxtaobod tumani', 'ru' => 'Пахтаабадский район', 'en' => 'Pakhtaabad district'],
                    ['uz' => 'Shahrixon tumani', 'ru' => 'Шахриханский район', 'en' => 'Shahrikhan district'],
                    ['uz' => 'Xoʻjaobod tumani', 'ru' => 'Ходжаабадский район', 'en' => 'Khojaabad district'],
                ],
            ],
            [
                'name' => ['uz' => 'Buxoro viloyati', 'ru' => 'Бухарская область', 'en' => 'Bukhara region'],
                'cities' => [
                    ['uz' => 'Buxoro', 'ru' => 'Бухара', 'en' => 'Bukhara'],
                    ['uz' => 'Kogon', 'ru' => 'Каган', 'en' => 'Kagan'],
                    ['uz' => 'Buxoro tumani', 'ru' => 'Бухарский район', 'en' => 'Bukhara district'],
                    ['uz' => 'Vobkent tumani', 'ru' => 'Вабкентский район', 'en' => 'Vabkent district'],
                    ['uz' => 'Jondor tumani', 'ru' => 'Жондорский район', 'en' => 'Jondor district'],
                    ['uz' => 'Kogon tumani', 'ru' => 'Каганский район', 'en' => 'Kagan district'],
                    ['uz' => 'Olot tumani', 'ru' => 'Алатский район', 'en' => 'Alat district'],
                    ['uz' => 'Peshku tumani', 'ru' => 'Пешкунский район', 'en' => 'Peshku district'],
                    ['uz' => 'Romitan tumani', 'ru' => 'Ромитанский район', 'en' => 'Romitan district'],
                    ['uz' => 'Shofirkon tumani', 'ru' => 'Шафирканский район', 'en' => 'Shafirkan district'],
                    ['uz' => 'Qorovulbozor tumani', 'ru' => 'Караулбазарский район', 'en' => 'Karaulbazar district'],
                    ['uz' => 'Qorakoʻl tumani', 'ru' => 'Каракульский район', 'en' => 'Karakul district'],
                    ['uz' => 'Gʻijduvon tumani', 'ru' => 'Гиждуванский район', 'en' => 'Gijduvan district'],
                ],
            ],
            [
                'name' => ['uz' => 'Fargʻona viloyati', 'ru' => 'Ферганская область', 'en' => 'Fergana region'],
                'cities' => [
                    ['uz' => 'Fargʻona', 'ru' => 'Фергана', 'en' => 'Fergana'],
                    ['uz' => 'Qoʻqon', 'ru' => 'Коканд', 'en' => 'Kokand'],
                    ['uz' => 'Quva', 'ru' => 'Кува', 'en' => 'Quva'],
                    ['uz' => 'Margʻilon', 'ru' => 'Маргилан', 'en' => 'Margilan'],
                    ['uz' => 'Oltiariq tumani', 'ru' => 'Алтыарыкский район', 'en' => 'Oltiariq district'],
                    ['uz' => 'Bagʻdod tumani', 'ru' => 'Багдадский район', 'en' => 'Baghdad district'],
                    ['uz' => 'Beshariq tumani', 'ru' => 'Бешарыкский район', 'en' => 'Beshariq district'],
                    ['uz' => 'Buvayda tumani', 'ru' => 'Бувайдинский район', 'en' => 'Buvayda district'],
                    ['uz' => 'Dangʻara tumani', 'ru' => 'Дангаринский район', 'en' => 'Dangara district'],
                    ['uz' => 'Yozyovon tumani', 'ru' => 'Язъяванский район', 'en' => 'Yazyavan district'],
                    ['uz' => 'Quva tumani', 'ru' => 'Кувинский район', 'en' => 'Quva district'],
                    ['uz' => 'Qoʻshtepa tumani', 'ru' => 'Куштепинский район', 'en' => 'Qoshtepa district'],
                    ['uz' => 'Rishton tumani', 'ru' => 'Риштанский район', 'en' => 'Rishtan district'],
                    ['uz' => 'Soʻx tumani', 'ru' => 'Сохский район', 'en' => 'Sokh district'],
                    ['uz' => 'Toshloq tumani', 'ru' => 'Ташлакский район', 'en' => 'Tashlak district'],
                    ['uz' => 'Oʻzbekiston tumani', 'ru' => 'Узбекистанский район', 'en' => 'Uzbekistan district'],
                    ['uz' => 'Uchkoʻprik tumani', 'ru' => 'Учкуприкский район', 'en' => 'Uchkuprik district'],
                    ['uz' => 'Fargʻona tumani', 'ru' => 'Ферганский район', 'en' => 'Fergana district'],
                    ['uz' => 'Furqat tumani', 'ru' => 'Фуркатский район', 'en' => 'Furqat district'],
                ],
            ],
            [
                'name' => ['uz' => 'Jizzax viloyati', 'ru' => 'Джизакская область', 'en' => 'Jizzakh region'],
                'cities' => [
                    ['uz' => 'Jizzax', 'ru' => 'Джизак', 'en' => 'Jizzakh'],
                    ['uz' => 'Arnasoy tumani', 'ru' => 'Арнасайский район', 'en' => 'Arnasay district'],
                    ['uz' => 'Baxmal tumani', 'ru' => 'Бахмальский район', 'en' => 'Bakhmal district'],
                    ['uz' => 'Doʻstlik tumani', 'ru' => 'Дустликский район', 'en' => 'Dustlik district'],
                    ['uz' => 'Zomin tumani', 'ru' => 'Заминский район', 'en' => 'Zamin district'],
                    ['uz' => 'Zafarobod tumani', 'ru' => 'Зафарабадский район', 'en' => 'Zafarabad district'],
                    ['uz' => 'Zarbdor tumani', 'ru' => 'Зарбдарский район', 'en' => 'Zarbdar district'],
                    ['uz' => 'Mirzachoʻl tumani', 'ru' => 'Мирзачульский район', 'en' => 'Mirzachul district'],
                    ['uz' => 'Paxtakor tumani', 'ru' => 'Пахтакорский район', 'en' => 'Pakhtakor district'],
                    ['uz' => 'Forish tumani', 'ru' => 'Фаришский район', 'en' => 'Farish district'],
                    ['uz' => 'Sharof Rashidov tumani', 'ru' => 'Шараф Рашидовский район', 'en' => 'Sharof Rashidov district'],
                    ['uz' => 'Gʻallaorol tumani', 'ru' => 'Галляаральский район', 'en' => 'Gallaaral district'],
                    ['uz' => 'Yangiobod tumani', 'ru' => 'Янгиабадский район', 'en' => 'Yangiabad district'],
                ],
            ],
            [
                'name' => ['uz' => 'Xorazm viloyati', 'ru' => 'Хорезмская область', 'en' => 'Khorezm region'],
                'cities' => [
                    ['uz' => 'Urganch', 'ru' => 'Ургенч', 'en' => 'Urgench'],
                    ['uz' => 'Xiva', 'ru' => 'Хива', 'en' => 'Khiva'],
                    ['uz' => 'Bogʻot tumani', 'ru' => 'Багатский район', 'en' => 'Bagat district'],
                    ['uz' => 'Gurlan tumani', 'ru' => 'Гурленский район', 'en' => 'Gurlan district'],
                    ['uz' => 'Xonqa tumani', 'ru' => 'Ханкинский район', 'en' => 'Khanka district'],
                    ['uz' => 'Xazorasp tumani', 'ru' => 'Хазараспский район', 'en' => 'Hazorasp district'],
                    ['uz' => 'Xiva tumani', 'ru' => 'Хивинский район', 'en' => 'Khiva district'],
                    ['uz' => 'Qoʻshkoʻpir tumani', 'ru' => 'Кошкупырский район', 'en' => 'Qoshkopir district'],
                    ['uz' => 'Shovot tumani', 'ru' => 'Шаватский район', 'en' => 'Shavat district'],
                    ['uz' => 'Urganch tumani', 'ru' => 'Ургенчский район', 'en' => 'Urgench district'],
                    ['uz' => 'Yangiariq tumani', 'ru' => 'Янгиарыкский район', 'en' => 'Yangiariq district'],
                    ['uz' => 'Yangibozor tumani', 'ru' => 'Янгибазарский район', 'en' => 'Yangibazar district'],
                    ['uz' => 'Tuproqqalʼa tumani', 'ru' => 'Тупроккалинский район', 'en' => 'Tupraqqala district'],
                ],
            ],
            [
                'name' => ['uz' => 'Namangan viloyati', 'ru' => 'Наманганская область', 'en' => 'Namangan region'],
                'cities' => [
                    ['uz' => 'Namangan', 'ru' => 'Наманган', 'en' => 'Namangan'],
                    ['uz' => 'Chust', 'ru' => 'Чуст', 'en' => 'Chust'],
                    ['uz' => 'Kosonsoy tumani', 'ru' => 'Касансайский район', 'en' => 'Kasansay district'],
                    ['uz' => 'Mingbuloq tumani', 'ru' => 'Мингбулакский район', 'en' => 'Mingbulak district'],
                    ['uz' => 'Namangan tumani', 'ru' => 'Наманганский район', 'en' => 'Namangan district'],
                    ['uz' => 'Norin tumani', 'ru' => 'Нарынский район', 'en' => 'Naryn district'],
                    ['uz' => 'Pop tumani', 'ru' => 'Папский район', 'en' => 'Pop district'],
                    ['uz' => 'Toʻraqoʻrgʻon tumani', 'ru' => 'Туракурганский район', 'en' => 'Turaqurgan district'],
                    ['uz' => 'Uychi tumani', 'ru' => 'Уйчинский район', 'en' => 'Uychi district'],
                    ['uz' => 'Uchqoʻrgʻon tumani', 'ru' => 'Учкурганский район', 'en' => 'Uchqurgan district'],
                    ['uz' => 'Chortoq tumani', 'ru' => 'Чартакский район', 'en' => 'Chartak district'],
                    ['uz' => 'Chust tumani', 'ru' => 'Чустский район', 'en' => 'Chust district'],
                    ['uz' => 'Yangiqoʻrgʻon tumani', 'ru' => 'Янгикурганский район', 'en' => 'Yangiqurgan district'],
                    ['uz' => 'Davlatobod tumani', 'ru' => 'Давлатабадский район', 'en' => 'Davlatabad district'],
                ],
            ],
            [
                'name' => ['uz' => 'Navoiy viloyati', 'ru' => 'Навоийская область', 'en' => 'Navoi region'],
                'cities' => [
                    ['uz' => 'Navoiy', 'ru' => 'Навои', 'en' => 'Navoi'],
                    ['uz' => 'Zarafshon', 'ru' => 'Зарафшан', 'en' => 'Zarafshan'],
                    ['uz' => 'Karmana tumani', 'ru' => 'Карманинский район', 'en' => 'Karmana district'],
                    ['uz' => 'Konimex tumani', 'ru' => 'Канимехский район', 'en' => 'Kanimekh district'],
                    ['uz' => 'Qiziltepa tumani', 'ru' => 'Кызылтепинский район', 'en' => 'Kyzyltepa district'],
                    ['uz' => 'Xatirchi tumani', 'ru' => 'Хатырчинский район', 'en' => 'Khatirchi district'],
                    ['uz' => 'Navbahor tumani', 'ru' => 'Навбахорский район', 'en' => 'Navbahor district'],
                    ['uz' => 'Nurota tumani', 'ru' => 'Нуратинский район', 'en' => 'Nurata district'],
                    ['uz' => 'Tomdi tumani', 'ru' => 'Тамдынский район', 'en' => 'Tamdy district'],
                    ['uz' => 'Uchquduq tumani', 'ru' => 'Учкудукский район', 'en' => 'Uchkuduk district'],
                ],
            ],
            [
                'name' => ['uz' => 'Qashqadaryo viloyati', 'ru' => 'Кашкадарьинская область', 'en' => 'Qashqadaryo region'],
                'cities' => [
                    ['uz' => 'Qarshi', 'ru' => 'Карши', 'en' => 'Karshi'],
                    ['uz' => 'Shahrisabz', 'ru' => 'Шахрисабз', 'en' => 'Shahrisabz'],
                    ['uz' => 'Gʻuzor tumani', 'ru' => 'Гузарский район', 'en' => 'Guzar district'],
                    ['uz' => 'Dehqonobod tumani', 'ru' => 'Дехканабадский район', 'en' => 'Dehkanabad district'],
                    ['uz' => 'Qamashi tumani', 'ru' => 'Камашинский район', 'en' => 'Kamashi district'],
                    ['uz' => 'Qarshi tumani', 'ru' => 'Каршинский район', 'en' => 'Karshi district'],
                    ['uz' => 'Koson tumani', 'ru' => 'Касанский район', 'en' => 'Kasan district'],
                    ['uz' => 'Kitob tumani', 'ru' => 'Китабский район', 'en' => 'Kitab district'],
                    ['uz' => 'Mirishkor tumani', 'ru' => 'Миришкорский район', 'en' => 'Mirishkor district'],
                    ['uz' => 'Muborak tumani', 'ru' => 'Мубарекский район', 'en' => 'Mubarek district'],
                    ['uz' => 'Nishon tumani', 'ru' => 'Нишанский район', 'en' => 'Nishan district'],
                    ['uz' => 'Kasbi tumani', 'ru' => 'Касбинский район', 'en' => 'Kasbi district'],
                    ['uz' => 'Chiroqchi tumani', 'ru' => 'Чиракчинский район', 'en' => 'Chirakchi district'],
                    ['uz' => 'Shahrisabz tumani', 'ru' => 'Шахрисабзский район', 'en' => 'Shahrisabz district'],
                    ['uz' => 'Yakkabogʻ tumani', 'ru' => 'Яккабагский район', 'en' => 'Yakkabag district'],
                ],
            ],
            [
                'name' => ['uz' => 'Samarqand viloyati', 'ru' => 'Самаркандская область', 'en' => 'Samarkand region'],
                'cities' => [
                    ['uz' => 'Samarqand', 'ru' => 'Самарканд', 'en' => 'Samarkand'],
                    ['uz' => 'Kattaqoʻrgʻon', 'ru' => 'Каттакурган', 'en' => 'Kattakurgan'],
                    ['uz' => 'Bulungʻur tumani', 'ru' => 'Булунгурский район', 'en' => 'Bulungur district'],
                    ['uz' => 'Jomboy tumani', 'ru' => 'Джамбайский район', 'en' => 'Jambay district'],
                    ['uz' => 'Ishtixon tumani', 'ru' => 'Иштыханский район', 'en' => 'Ishtihan district'],
                    ['uz' => 'Kattaqoʻrgʻon tumani', 'ru' => 'Каттакурганский район', 'en' => 'Kattakurgan district'],
                    ['uz' => 'Qoʻshrabot tumani', 'ru' => 'Кошрабадский район', 'en' => 'Koshrabad district'],
                    ['uz' => 'Narpay tumani', 'ru' => 'Нарпайский район', 'en' => 'Narpay district'],
                    ['uz' => 'Nurobod tumani', 'ru' => 'Нурабадский район', 'en' => 'Nurabad district'],
                    ['uz' => 'Oqdaryo tumani', 'ru' => 'Акдарьинский район', 'en' => 'Akdarya district'],
                    ['uz' => 'Payariq tumani', 'ru' => 'Пайарыкский район', 'en' => 'Payariq district'],
                    ['uz' => 'Pastdargʻom tumani', 'ru' => 'Пастдаргомский район', 'en' => 'Pastdargom district'],
                    ['uz' => 'Paxtachi tumani', 'ru' => 'Пахтачийский район', 'en' => 'Pakhtachi district'],
                    ['uz' => 'Samarqand tumani', 'ru' => 'Самаркандский район', 'en' => 'Samarkand district'],
                    ['uz' => 'Toyloq tumani', 'ru' => 'Тайлякский район', 'en' => 'Taylak district'],
                    ['uz' => 'Urgut tumani', 'ru' => 'Ургутский район', 'en' => 'Urgut district'],
                ],
            ],
            [
                'name' => ['uz' => 'Sirdaryo viloyati', 'ru' => 'Сырдарьинская область', 'en' => 'Syrdarya region'],
                'cities' => [
                    ['uz' => 'Guliston', 'ru' => 'Гулистан', 'en' => 'Gulistan'],
                    ['uz' => 'Shirin', 'ru' => 'Ширин', 'en' => 'Shirin'],
                    ['uz' => 'Yangiyer', 'ru' => 'Янгиер', 'en' => 'Yangier'],
                    ['uz' => 'Oqoltin tumani', 'ru' => 'Акалтынский район', 'en' => 'Akaltin district'],
                    ['uz' => 'Boyovut tumani', 'ru' => 'Баяутский район', 'en' => 'Bayaut district'],
                    ['uz' => 'Guliston tumani', 'ru' => 'Гулистанский район', 'en' => 'Gulistan district'],
                    ['uz' => 'Mirzaobod tumani', 'ru' => 'Мирзаабадский район', 'en' => 'Mirzaabad district'],
                    ['uz' => 'Sardoba tumani', 'ru' => 'Сардобинский район', 'en' => 'Sardoba district'],
                    ['uz' => 'Sayxunobod tumani', 'ru' => 'Сайхунабадский район', 'en' => 'Saykhunabad district'],
                    ['uz' => 'Sirdaryo tumani', 'ru' => 'Сырдарьинский район', 'en' => 'Syrdarya district'],
                    ['uz' => 'Xovos tumani', 'ru' => 'Хавастский район', 'en' => 'Khavast district'],
                ],
            ],
            [
                'name' => ['uz' => 'Surxondaryo viloyati', 'ru' => 'Сурхандарьинская область', 'en' => 'Surkhandarya region'],
                'cities' => [
                    ['uz' => 'Termiz', 'ru' => 'Термез', 'en' => 'Termez'],
                    ['uz' => 'Angor tumani', 'ru' => 'Ангорский район', 'en' => 'Angor district'],
                    ['uz' => 'Boysun tumani', 'ru' => 'Байсунский район', 'en' => 'Baysun district'],
                    ['uz' => 'Denov tumani', 'ru' => 'Денауский район', 'en' => 'Denau district'],
                    ['uz' => 'Jarqoʻrgʻon tumani', 'ru' => 'Джаркурганский район', 'en' => 'Jarkurgan district'],
                    ['uz' => 'Qumqoʻrgʻon tumani', 'ru' => 'Кумкурганский район', 'en' => 'Kumkurgan district'],
                    ['uz' => 'Qiziriq tumani', 'ru' => 'Кизирикский район', 'en' => 'Kizirik district'],
                    ['uz' => 'Muzrabot tumani', 'ru' => 'Музрабадский район', 'en' => 'Muzrabad district'],
                    ['uz' => 'Oltinsoy tumani', 'ru' => 'Алтынсайский район', 'en' => 'Altinsay district'],
                    ['uz' => 'Sariosiyo tumani', 'ru' => 'Сариасийский район', 'en' => 'Sariasiya district'],
                    ['uz' => 'Sherobod tumani', 'ru' => 'Шерабадский район', 'en' => 'Sherabad district'],
                    ['uz' => 'Shoʻrchi tumani', 'ru' => 'Шурчинский район', 'en' => 'Shurchi district'],
                    ['uz' => 'Termiz tumani', 'ru' => 'Термезский район', 'en' => 'Termez district'],
                    ['uz' => 'Uzun tumani', 'ru' => 'Узунский район', 'en' => 'Uzun district'],
                    ['uz' => 'Bandixon tumani', 'ru' => 'Бандиханский район', 'en' => 'Bandikhan district'],
                ],
            ],
            [
                'name' => ['uz' => 'Qoraqalpogʻiston Respublikasi', 'ru' => 'Республика Каракалпакстан', 'en' => 'Republic of Karakalpakstan'],
                'cities' => [
                    ['uz' => 'Nukus', 'ru' => 'Нукус', 'en' => 'Nukus'],
                    ['uz' => 'Amudaryo tumani', 'ru' => 'Амударьинский район', 'en' => 'Amudarya district'],
                    ['uz' => 'Beruniy tumani', 'ru' => 'Берунийский район', 'en' => 'Beruniy district'],
                    ['uz' => 'Boʻzatov tumani', 'ru' => 'Бозатауский район', 'en' => 'Bozatau district'],
                    ['uz' => 'Ellikqalʼa tumani', 'ru' => 'Элликкалинский район', 'en' => 'Ellikqala district'],
                    ['uz' => 'Kegeyli tumani', 'ru' => 'Кегейлийский район', 'en' => 'Kegeyli district'],
                    ['uz' => 'Moʻynoq tumani', 'ru' => 'Муйнакский район', 'en' => 'Muynak district'],
                    ['uz' => 'Nukus tumani', 'ru' => 'Нукусский район', 'en' => 'Nukus district'],
                    ['uz' => 'Qonlikoʻl tumani', 'ru' => 'Канлыкульский район', 'en' => 'Kanlikul district'],
                    ['uz' => 'Qoʻngʻirot tumani', 'ru' => 'Кунградский район', 'en' => 'Kungrad district'],
                    ['uz' => 'Qoraoʻzak tumani', 'ru' => 'Караузякский район', 'en' => 'Karauzak district'],
                    ['uz' => 'Shumanay tumani', 'ru' => 'Шуманайский район', 'en' => 'Shumanay district'],
                    ['uz' => 'Taxtakoʻpir tumani', 'ru' => 'Тахтакупырский район', 'en' => 'Takhtakupir district'],
                    ['uz' => 'Toʻrtkoʻl tumani', 'ru' => 'Турткульский район', 'en' => 'Turtkul district'],
                    ['uz' => 'Xoʻjayli tumani', 'ru' => 'Ходжейлийский район', 'en' => 'Khojeyli district'],
                    ['uz' => 'Chimboy tumani', 'ru' => 'Чимбайский район', 'en' => 'Chimbay district'],
                    ['uz' => 'Taxiatosh tumani', 'ru' => 'Тахиаташский район', 'en' => 'Takhiatash district'],
                ],
            ],
        ];

        foreach ($regionsData as $regionData) {
            $region = Region::create([
                'name' => $regionData['name'],
                'sort_order' => 0,
                'is_active' => true,
            ]);

            foreach ($regionData['cities'] as $index => $cityName) {
                City::create([
                    'region_id' => $region->id,
                    'name' => $cityName,
                    'sort_order' => $index,
                    'is_active' => true,
                ]);
            }
        }
    }
}
